apiVersion: v1
kind: Secret
metadata:
  name: github-registry-secret
  namespace: fintech-prod
  annotations:
    kubernetes.io/description: "GitHub Container Registry authentication"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "github-registry"
    vault.hashicorp.com/agent-inject-secret-config: "secret/github/registry"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiZGV2b3BzLWF1dG9tYXRpb24iLCJwYXNzd29yZCI6ImdocF9SNGw5VDBrZW5fQjNmNGtlX2V4YW1wbGVfdG9rZW4xMjM0NSIsImF1dGgiOiJaR1YyYjNCekxXRjFkRzl0WVhScGIyNDZaMmh3WDFJMGJEbFVNR3RsYmw5Q00yWTBhMlZmWlhoaGJYQnNaVjkwYjJ0bGJqRXlNelExIn19fQ==